### ISSUE TITLE
TwythonStreamer set up details

### ISSUE THREAD

**Issue by Craig88** [hothod3rd/TwitterMainBotHashtagScrubber#2]
This is cool. I can tell it's using `TwythonStreamer` to fetch some tweets and display on a webpage.

Can you update the readme to include some instructions for setting up this project? Are the API details available to read somewhere else? Is there anything else I need to make sure I've got installed?

**Comment by hothod3rd** [comment]
Readme updated in: 8b61b1a6c72db76263f80186eb3c242ab35322bd
